import BigNumber from 'bignumber.js';

import type { SpokePool } from 'types';
import {
  vBnbSpokeBluechips,
  vBusdSpokeBluechips,
  vEthSpokeBstock,
  vUsdcSpokeBstock,
  vUsdcSpokeRwa,
  vUsdtSpokeBluechips,
  vUsdtSpokeBstock,
  vWbnbSpokeBluechips,
  vWethSpokeRwa,
  vXvsSpokeBstock,
} from '../vTokens';
import { buildSpokeAsset } from './buildSpokeAsset';

export const spokePools: SpokePool[] = [
  {
    comptrollerAddress: '0x11960c84d6c4F2a978a12372721C3A6A88C78f4c',
    name: 'bStock',
    description: 'Borrow against bStock assets.',
    isIsolated: true,
    eModeGroups: [],
    userSupplyBalanceCents: new BigNumber(858000),
    userBorrowBalanceCents: new BigNumber(126432),
    userBorrowLimitCents: new BigNumber(429000),
    userLiquidationThresholdCents: new BigNumber(514800),
    userYearlyEarningsCents: new BigNumber(-5753),
    userHealthFactor: 4.07,
    assets: [
      buildSpokeAsset({
        vToken: vUsdtSpokeBstock,
        tokenPriceCents: 100,
        isBorrowable: true,
        isSupplyAllowlistEnabled: true,
        borrowApyPercentage: 4.55,
        supplyApyPercentage: 3.1,
        supplyBalanceTokens: 10_000_000,
        borrowBalanceTokens: 8_430_000,
        cashTokens: 1_360_000,
        supplyCapTokens: 20_000_000,
        borrowCapTokens: 12_000_000,
        userBorrowBalanceTokens: 1264.32,
        userWalletBalanceTokens: 5200,
      }),
      buildSpokeAsset({
        vToken: vUsdcSpokeBstock,
        tokenPriceCents: 100,
        isBorrowable: true,
        isSupplyAllowlistEnabled: true,
        borrowApyPercentage: 6.2,
        supplyApyPercentage: 4.4,
        supplyBalanceTokens: 12_400_000,
        borrowBalanceTokens: 9_320_000,
        cashTokens: 2_920_000,
        supplyCapTokens: 20_000_000,
        borrowCapTokens: 12_000_000,
        userWalletBalanceTokens: 800,
      }),
      buildSpokeAsset({
        vToken: vXvsSpokeBstock,
        tokenPriceCents: 715,
        isBorrowable: false,
        collateralFactor: 0.5,
        liquidationThresholdPercentage: 60,
        liquidationPenaltyPercentage: 10,
        supplyBalanceTokens: 150_000,
        cashTokens: 150_000,
        supplyCapTokens: 300_000,
        userSupplyBalanceTokens: 1200,
        userWalletBalanceTokens: 340,
      }),
      buildSpokeAsset({
        vToken: vEthSpokeBstock,
        tokenPriceCents: 320_000,
        isBorrowable: false,
        collateralFactor: 0.6,
        liquidationThresholdPercentage: 70,
        liquidationPenaltyPercentage: 10,
        supplyBalanceTokens: 412,
        cashTokens: 412,
        supplyCapTokens: 500,
        userWalletBalanceTokens: 2.4,
      }),
    ],
  },
  {
    comptrollerAddress: '0x26D0Df4e36F3d3b6A0b4Cc2F8b5A1e9C7d0F3a12',
    name: 'Bluechips',
    description: 'Borrow against bluechip assets.',
    isIsolated: true,
    eModeGroups: [],
    userSupplyBalanceCents: new BigNumber(0),
    userBorrowBalanceCents: new BigNumber(0),
    userBorrowLimitCents: new BigNumber(0),
    userLiquidationThresholdCents: new BigNumber(0),
    userYearlyEarningsCents: new BigNumber(0),
    assets: [
      buildSpokeAsset({
        vToken: vUsdtSpokeBluechips,
        tokenPriceCents: 100,
        isBorrowable: true,
        isSupplyAllowlistEnabled: true,
        borrowApyPercentage: 4.34,
        supplyApyPercentage: 2.9,
        supplyBalanceTokens: 9_800_000,
        borrowBalanceTokens: 8_430_000,
        cashTokens: 1_360_000,
        supplyCapTokens: 15_000_000,
        borrowCapTokens: 10_000_000,
        userWalletBalanceTokens: 5200,
      }),
      buildSpokeAsset({
        vToken: vBusdSpokeBluechips,
        tokenPriceCents: 100,
        isBorrowable: true,
        isSupplyAllowlistEnabled: true,
        borrowApyPercentage: 2.75,
        supplyApyPercentage: 1.8,
        supplyBalanceTokens: 14_200_000,
        borrowBalanceTokens: 12_430_000,
        cashTokens: 2_710_000,
        supplyCapTokens: 20_000_000,
        borrowCapTokens: 14_000_000,
        disabledTokenActions: ['borrow'],
      }),
      buildSpokeAsset({
        vToken: vBnbSpokeBluechips,
        tokenPriceCents: 62_000,
        isBorrowable: false,
        collateralFactor: 0.8,
        liquidationThresholdPercentage: 88,
        liquidationPenaltyPercentage: 10,
        supplyBalanceTokens: 4200,
        cashTokens: 4200,
        supplyCapTokens: 6000,
        userWalletBalanceTokens: 12.5,
      }),
      buildSpokeAsset({
        vToken: vWbnbSpokeBluechips,
        tokenPriceCents: 62_000,
        isBorrowable: false,
        collateralFactor: 0.75,
        liquidationThresholdPercentage: 85,
        liquidationPenaltyPercentage: 10,
        supplyBalanceTokens: 1800,
        cashTokens: 1800,
        supplyCapTokens: 4000,
      }),
    ],
  },
  {
    comptrollerAddress: '0x37E1Ea5F47a4e6C7b3D2f1A0c9B8e7D6f5A4c3B2',
    name: 'RWA',
    description: 'Borrow against RWA assets.',
    isIsolated: true,
    eModeGroups: [],
    userSupplyBalanceCents: new BigNumber(0),
    userBorrowBalanceCents: new BigNumber(0),
    userBorrowLimitCents: new BigNumber(0),
    userLiquidationThresholdCents: new BigNumber(0),
    userYearlyEarningsCents: new BigNumber(0),
    assets: [
      buildSpokeAsset({
        vToken: vUsdcSpokeRwa,
        tokenPriceCents: 100,
        isBorrowable: true,
        isSupplyAllowlistEnabled: true,
        borrowApyPercentage: 6.01,
        supplyApyPercentage: 4.2,
        supplyBalanceTokens: 11_200_000,
        borrowBalanceTokens: 9_320_000,
        cashTokens: 2_920_000,
        supplyCapTokens: 18_000_000,
        borrowCapTokens: 12_000_000,
      }),
      buildSpokeAsset({
        vToken: vWethSpokeRwa,
        tokenPriceCents: 320_000,
        isBorrowable: false,
        collateralFactor: 0.6,
        liquidationThresholdPercentage: 70,
        liquidationPenaltyPercentage: 10,
        supplyBalanceTokens: 132,
        cashTokens: 132,
        supplyCapTokens: 200,
      }),
    ],
  },
];
