enableScripts: true

plugins:
  - path: .yarn/plugins/yarn-plugin-generate-after-install.cjs
    spec: "@venusprotocol/yarn-plugin-generate-after-install"

nodeLinker: node-modules

# In minutes.
npmMinimalAgeGate: 10080
