version: "3.9"

services:
  venus-ui-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command:
      - sh
      - -c
      - |
        npm install
        npm start
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/app
    restart: always

  venus-ui-prod:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:80
    restart: always
