/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Provider } from '@ethersproject/providers';
import { Contract, Signer, utils } from 'ethers';

import type { JumpRateModelV2, JumpRateModelV2Interface } from '../JumpRateModelV2';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'baseRatePerYear',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'multiplierPerYear',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'jumpMultiplierPerYear',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'kink_',
        type: 'uint256',
      },
      {
        internalType: 'contract IAccessControlManagerV8',
        name: 'accessControlManager_',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'calledContract',
        type: 'address',
      },
      {
        internalType: 'string',
        name: 'methodSignature',
        type: 'string',
      },
    ],
    name: 'Unauthorized',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'baseRatePerBlock',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'multiplierPerBlock',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'jumpMultiplierPerBlock',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'kink',
        type: 'uint256',
      },
    ],
    name: 'NewInterestParams',
    type: 'event',
  },
  {
    inputs: [],
    name: 'accessControlManager',
    outputs: [
      {
        internalType: 'contract IAccessControlManagerV8',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'baseRatePerBlock',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'cash',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'borrows',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'reserves',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'badDebt',
        type: 'uint256',
      },
    ],
    name: 'getBorrowRate',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'cash',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'borrows',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'reserves',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'reserveFactorMantissa',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'badDebt',
        type: 'uint256',
      },
    ],
    name: 'getSupplyRate',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isInterestRateModel',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'jumpMultiplierPerBlock',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'kink',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'multiplierPerBlock',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'baseRatePerYear',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'multiplierPerYear',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'jumpMultiplierPerYear',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'kink_',
        type: 'uint256',
      },
    ],
    name: 'updateJumpRateModel',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'cash',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'borrows',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'reserves',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'badDebt',
        type: 'uint256',
      },
    ],
    name: 'utilizationRate',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
] as const;

export class JumpRateModelV2__factory {
  static readonly abi = _abi;
  static createInterface(): JumpRateModelV2Interface {
    return new utils.Interface(_abi) as JumpRateModelV2Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): JumpRateModelV2 {
    return new Contract(address, _abi, signerOrProvider) as JumpRateModelV2;
  }
}
