enum FunctionKey {
  // Queries
  GET_VAI_TREASURY_PERCENTAGE = 'GET_VAI_TREASURY_PERCENTAGE',
  GET_MARKETS = 'GET_MARKETS',
  GET_ASSETS_IN_ACCOUNT = 'GET_ASSETS_IN_ACCOUNT',
  GET_VTOKEN_BALANCES_ALL = 'GET_VTOKEN_BALANCES_ALL',
  GET_HYPOTHETICAL_LIQUIDITY = 'GET_HYPOTHETICAL_LIQUIDITY',
  GET_VENUS_INITIAL_INDEX = 'GET_VENUS_INITIAL_INDEX',
  GET_VENUS_ACCRUED = 'GET_VENUS_ACCRUED',
  GET_VENUS_VAI_STATE = 'GET_VENUS_VAI_STATE',
  GET_MINTED_VAI = 'GET_MINTED_VAI',
  GET_VENUS_VAI_MINTER_INDEX = 'GET_VENUS_VAI_MINTER_INDEX',

  // Mutations
  REQUEST_FAUCET_FUNDS = 'REQUEST_FAUCET_FUNDS',
  MINT_VAI = 'MINT_VAI',
  ENTER_MARKETS = 'ENTER_MARKETS',
  EXIT_MARKET = 'EXIT_MARKET',
  REPAY_VAI = 'REPAY_VAI',
  APPROVE_TOKEN = 'APPROVE_TOKEN',
  CLAIM_XVS_REWARD = 'CLAIM_XVS_REWARD',
}

export default FunctionKey;
