export type ColumnName =
  | 'asset'
  | 'supplyApyLtv'
  | 'labeledSupplyApyLtv'
  | 'borrowApy'
  | 'labeledBorrowApy'
  | 'pool'
  | 'riskLevel'
  | 'collateral'
  | 'walletBalance'
  | 'supplyBalance'
  | 'borrowBalance'
  | 'treasuryTotalBorrow'
  | 'treasuryTotalSupply'
  | 'liquidity'
  | 'percentOfLimit';
