import { iconSrcs } from '../../generated/manifests/chainIcons';
import { bnb, eth } from '../../tokens/nativeTokens';
import { type Chain, ChainId } from '../../types';

export const opBnbTestnetFourierForkTimestamp = new Date('2025-10-06 03:00:00 AM UTC');

const now = new Date();
const isPassedOpBnbTestnetFourierFork = now >= opBnbTestnetFourierForkTimestamp;

export const chains: {
  [chainId in ChainId]: Chain;
} = {
  [ChainId.BSC_MAINNET]: {
    name: 'BNB Chain',
    iconSrc: iconSrcs.bsc,
    // DEV ONLY
    // explorerUrl: 'https://bscscan.com',
    // END DEV ONLY
    explorerUrl: 'https://virtual.binance.eu.rpc.tenderly.co/22d6bce7-7f9a-4d18-bac5-4544cc4b1d79',
    layerZeroScanUrl: 'https://layerzeroscan.com',
    safeWalletApiUrl: 'https://safe-transaction-bsc.safe.global',
    blockTimeMs: 750,
    blocksPerDay: 115200,
    corePoolComptrollerContractAddress: '0xfD36E2c2a6789Db23113685031d7F16329158384',
    nativeToken: bnb,
  },
  [ChainId.BSC_TESTNET]: {
    name: 'BNB testnet',
    iconSrc: iconSrcs.bsc,
    explorerUrl: 'https://testnet.bscscan.com',
    layerZeroScanUrl: 'https://testnet.layerzeroscan.com',
    blockTimeMs: 750,
    blocksPerDay: 115200,
    corePoolComptrollerContractAddress: '0x94d1820b2D1c7c7452A163983Dc888CEC546b77D',
    nativeToken: bnb,
  },
  [ChainId.OPBNB_MAINNET]: {
    name: 'opBNB',
    iconSrc: iconSrcs.opBnb,
    explorerUrl: 'https://opbnbscan.com',
    layerZeroScanUrl: 'https://layerzeroscan.com',
    // TODO: handle Fourier hard fork once we have a fixed date for it (https://github.com/bnb-chain/opbnb/releases/tag/v0.5.4)
    blockTimeMs: 500,
    blocksPerDay: 172800,
    corePoolComptrollerContractAddress: '0xD6e3E2A1d8d95caE355D15b3b9f8E5c2511874dd',
    nativeToken: bnb,
  },
  [ChainId.OPBNB_TESTNET]: {
    name: 'opBNB testnet',
    iconSrc: iconSrcs.opBnb,
    explorerUrl: 'https://testnet.opbnbscan.com',
    layerZeroScanUrl: 'https://testnet.layerzeroscan.com',
    blockTimeMs: isPassedOpBnbTestnetFourierFork ? 250 : 500,
    blocksPerDay: isPassedOpBnbTestnetFourierFork ? 345600 : 172800,
    corePoolComptrollerContractAddress: '0x2FCABb31E57F010D623D8d68e1E18Aed11d5A388',
    nativeToken: bnb,
  },
  [ChainId.ETHEREUM]: {
    name: 'Ethereum',
    iconSrc: iconSrcs.eth,
    explorerUrl: 'https://etherscan.io',
    layerZeroScanUrl: 'https://layerzeroscan.com',
    safeWalletApiUrl: 'https://safe-transaction-mainnet.safe.global',
    blockTimeMs: 12000,
    blocksPerDay: 7200,
    corePoolComptrollerContractAddress: '0x687a01ecF6d3907658f7A7c714749fAC32336D1B',
    nativeToken: eth,
  },
  [ChainId.SEPOLIA]: {
    name: 'Sepolia',
    iconSrc: iconSrcs.eth,
    explorerUrl: 'https://sepolia.etherscan.io',
    layerZeroScanUrl: 'https://testnet.layerzeroscan.com',
    safeWalletApiUrl: 'https://safe-transaction-sepolia.safe.global',
    blockTimeMs: 12000,
    blocksPerDay: 7200,
    corePoolComptrollerContractAddress: '0x7Aa39ab4BcA897F403425C9C6FDbd0f882Be0D70',
    nativeToken: eth,
  },
  [ChainId.ARBITRUM_ONE]: {
    name: 'Arbitrum One',
    iconSrc: iconSrcs.arbitrumOne,
    explorerUrl: 'https://arbiscan.io',
    layerZeroScanUrl: 'https://layerzeroscan.com',
    safeWalletApiUrl: 'https://safe-transaction-arbitrum.safe.global',
    corePoolComptrollerContractAddress: '0x317c1A5739F39046E20b08ac9BeEa3f10fD43326',
    nativeToken: eth,
  },
  [ChainId.ARBITRUM_SEPOLIA]: {
    name: 'Arbitrum Sepolia',
    iconSrc: iconSrcs.arbitrumOne,
    explorerUrl: 'https://sepolia.arbiscan.io',
    layerZeroScanUrl: 'https://testnet.layerzeroscan.com',
    corePoolComptrollerContractAddress: '0x006D44b6f5927b3eD83bD0c1C36Fb1A3BaCaC208',
    nativeToken: eth,
  },
  [ChainId.ZKSYNC_MAINNET]: {
    name: 'ZKsync',
    iconSrc: iconSrcs.zkSync,
    explorerUrl: 'https://explorer.zksync.io',
    layerZeroScanUrl: 'https://layerzeroscan.com',
    safeWalletApiUrl: 'https://safe-transaction-zksync.safe.global',
    corePoolComptrollerContractAddress: '0xddE4D098D9995B659724ae6d5E3FB9681Ac941B1',
    nativeToken: eth,
  },
  [ChainId.ZKSYNC_SEPOLIA]: {
    name: 'ZKsync Sepolia',
    iconSrc: iconSrcs.zkSync,
    explorerUrl: 'https://sepolia.explorer.zksync.io',
    layerZeroScanUrl: 'https://testnet.layerzeroscan.com',
    corePoolComptrollerContractAddress: '0xC527DE08E43aeFD759F7c0e6aE85433923064669',
    nativeToken: eth,
  },
  [ChainId.OPTIMISM_MAINNET]: {
    name: 'Optimism',
    iconSrc: iconSrcs.optimism,
    explorerUrl: 'https://optimistic.etherscan.io',
    layerZeroScanUrl: 'https://layerzeroscan.com',
    safeWalletApiUrl: 'https://safe-transaction-optimism.safe.global',
    corePoolComptrollerContractAddress: '0x5593FF68bE84C966821eEf5F0a988C285D5B7CeC',
    nativeToken: eth,
  },
  [ChainId.OPTIMISM_SEPOLIA]: {
    name: 'Optimism Sepolia',
    iconSrc: iconSrcs.optimism,
    explorerUrl: 'https://sepolia-optimism.etherscan.io',
    layerZeroScanUrl: 'https://testnet.layerzeroscan.com',
    corePoolComptrollerContractAddress: '0x59d10988974223B042767aaBFb6D926863069535',
    nativeToken: eth,
  },
  [ChainId.BASE_MAINNET]: {
    name: 'Base',
    iconSrc: iconSrcs.base,
    explorerUrl: 'https://basescan.org',
    layerZeroScanUrl: 'https://layerzeroscan.com',
    safeWalletApiUrl: 'https://safe-transaction-base.safe.global',
    corePoolComptrollerContractAddress: '0x0C7973F9598AA62f9e03B94E92C967fD5437426C',
    nativeToken: eth,
  },
  [ChainId.BASE_SEPOLIA]: {
    name: 'Base Sepolia',
    iconSrc: iconSrcs.base,
    explorerUrl: 'https://sepolia.basescan.org',
    layerZeroScanUrl: 'https://testnet.layerzeroscan.com',
    safeWalletApiUrl: 'https://safe-transaction-base-sepolia.safe.global',
    corePoolComptrollerContractAddress: '0x272795dd6c5355CF25765F36043F34014454Eb5b',
    nativeToken: eth,
  },
  [ChainId.UNICHAIN_MAINNET]: {
    name: 'Unichain',
    iconSrc: iconSrcs.unichain,
    explorerUrl: 'https://uniscan.xyz',
    layerZeroScanUrl: 'https://layerzeroscan.com',
    corePoolComptrollerContractAddress: '0xe22af1e6b78318e1Fe1053Edbd7209b8Fc62c4Fe',
    nativeToken: eth,
  },
  [ChainId.UNICHAIN_SEPOLIA]: {
    name: 'Unichain Sepolia',
    iconSrc: iconSrcs.unichain,
    explorerUrl: 'https://sepolia.uniscan.xyz',
    layerZeroScanUrl: 'https://testnet.layerzeroscan.com',
    corePoolComptrollerContractAddress: '0xFeD3eAA668a6179c9E5E1A84e3A7d6883F06f7c1',
    nativeToken: eth,
  },
};
