name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # Required for OIDC
  contents: write # to be able to publish a GitHub release

env:
  NODE_OPTIONS: "--max_old_space_size=4096"
  VITE_ENV: "ci"
  CLI_NODE_REAL_API_KEY: ${{ secrets.CLI_NODE_REAL_API_KEY }}
  CLI_ALCHEMY_API_KEY: ${{ secrets.CLI_ALCHEMY_API_KEY }}

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install --immutable

          # Install required npm version to use trusted publisher
          # (https://docs.npmjs.com/trusted-publishers)
          npm install -g npm@11.5.1

      - name: Run tests and collect coverage
        run: yarn test --coverage

      # Bump package versions based on changesets and commit changes to the main branch
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          BLOB_READ_WRITE_TOKEN: ${{ secrets.VERCEL_BLOB_TOKEN }}
          IMG_CDN_URL: ${{ vars.IMG_CDN_URL }}
        run: |
          git config user.name toolsvenus
          git config user.email tools@venus.io
          git fetch origin
          git rebase --strategy-option=theirs origin/main

          npx changeset version

          if git diff -- "packages/chains/package.json" | grep -qE '^\+ *"version":'; then
            yarn workspace @venusprotocol/chains deploy-images
            yarn workspace @venusprotocol/chains build
          fi

          npx changeset publish

          git add -A
          git status
          git commit --verbose -a -m "chore: bump package versions" || exit 0
          git push
